name       : python-defusedxml
version    : 0.7.1
release    : 5
source     :
    - https://github.com/tiran/defusedxml/archive/refs/tags/v0.7.1.tar.gz : 93cdbc6c5c9d3dc08991a9804253933491a5a7f3c2d8583e54337e5469c73849
homepage   : https://github.com/tiran/defusedxml
license    : Python-2.0
component  : programming.python
summary    : Defuses XML bombs and other exploits
description: |
    XML bomb protection for Python stdlib modules
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
