name       : python-defusedxml
version    : 0.6.0
release    : 1
source     :
    - https://github.com/tiran/defusedxml/archive/v0.6.0.tar.gz : 9f4b51d234ff99e3b1f4244b189ca1fa33c05b5cbc60fcc910af423721fea0b6
license    : Python-2.0
component  : programming.python
summary    : Defuses XML bombs and other exploits
description: |
    XML bomb protection for Python stdlib modules
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test