name       : python-defusedxml
version    : 0.6.0
release    : 3
source     :
    - https://github.com/tiran/defusedxml/archive/v0.6.0.tar.gz : 9f4b51d234ff99e3b1f4244b189ca1fa33c05b5cbc60fcc910af423721fea0b6
homepage   : https://github.com/tiran/defusedxml
license    : Python-2.0
component  : programming.python
summary    : Defuses XML bombs and other exploits
description: |
    XML bomb protection for Python stdlib modules
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |-
    %python3_test
